const { command, isPrivate } = require("../lib/");
const axios = require("axios");

command(
  {
    pattern: "blackbox",
    fromMe: isPrivate,
    desc: "Chat with Blackbox AI",
    type: "tools",
  },
  async (message, match, m) => {
    // Ensure the user provides a query
    if (!match) {
      return await message.reply(
        "❗ Please provide a query for Blackbox AI.\n" +
        "Example: `.blackbox hello`"
      );
    }

    try {
      // Construct the API request URL
      const apiUrl = `https://nikka-api.vercel.app/blackbox?q=${encodeURIComponent(
        match
      )}&apiKey=nikka`;

      // Fetch the response from the API
      const response = await axios.get(apiUrl);

      if (response.data && response.data.data) {
        // Remove the unwanted part from the response
        const cleanResponse = response.data.data.replace(
          /Generated by BLACKBOX.AI, try unlimited chat https:\/\/www\.blackbox\.ai/g,
          ""
        ).trim();

        // Send the response to the user
        await message.reply(cleanResponse);
      } else {
        await message.reply("❗ No response from Blackbox AI. Please try again later.");
      }
    } catch (error) {
      console.error("Error with Blackbox API:", error);
      await message.reply("❗ An error occurred while connecting to Blackbox AI.");
    }
  }
);
